import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Map } from "react-map-gl";
import DeckGL from "@deck.gl/react/typed";
import { usePlot } from "../hooks/usePlot";
import ControlPanel from "../components/ControlPanel";
import DisplayPanel from "../components/DisplayPanel";
const inter = Inter({ subsets: ["latin"] });

const MAP_STYLE =
  "https://basemaps.cartocdn.com/gl/positron-nolabels-gl-style/style.json";

/**
 * Home Component
 * @remarks
 * Home React functional component for index page and initial point of the app, no props
 * @returns <Home/>
 */
function Home() {
  const {
    handleDataUpload,
    handleFloorHeightChange,
    handleNumberOfFloorChange,
    handlePlotScaleChange,
    plotArea,
    buildingArea,
    buildingFloorArea,
    buildingHeight,
    volume,
    layers,
    floors,
    floorHeight,
    plotScale,
    viewState,
  } = usePlot();

  return (
    <>
      <Head>
        <title>Plot 3D</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        data-testid={"home"}
        className={`${styles.main} ${inter.className}`}
        style={{ position: "relative" }}
      >
        <ControlPanel
          handleUpload={handleDataUpload}
          handlePlotScaleChange={handlePlotScaleChange}
          handleNumberOfFloorChange={handleNumberOfFloorChange}
          handleFloorHeightChange={handleFloorHeightChange}
          floorHeight={floorHeight}
          scale={plotScale}
          floors={floors}
        />
        <DisplayPanel
          buildingArea={buildingArea}
          buildingFloorArea={buildingFloorArea}
          buildingHeight={buildingHeight}
          volume={volume}
          plotArea={plotArea}
        />
        <DeckGL layers={layers} initialViewState={viewState} controller={true}>
          <Map
            mapboxAccessToken={
              "pk.eyJ1Ijoia2FtYWFsIiwiYSI6ImNpZzltZ2d6dDBxb3p1NGtqMzVqZjNrYWgifQ.5qWQL89rK4emLbp7xZLkeA"
            }
            mapStyle={MAP_STYLE}
          />
        </DeckGL>
      </main>
    </>
  );
}

export default Home;
